publishDir = "docs"
baseURL = "https://dpl-gc.github.io/"
languageCode = 'uk-ua'
title = 'КП ДМКЛ ПМР'
theme = "cleanwhite"

[menus]
  [[menus.main]]
    name = "Головна"
    url = "/"
    weight = 10 # Порядок в меню
  [[menus.main]]
    name = "Про нас" # Текст, що відображається в меню
    url = "/about/" # Шлях до сторінки. Зверніть увагу на слеші!
    weight = 20
  [[menus.main]]
    name = "Наша історія"
    url = "/about/history/"
    parent = "Про нас" # Цей пункт буде підпунктом "Про нас"
    weight = 10
  [[menus.main]]
    name = "Керівництво"
    url = "/about/boss/"
    parent = "Про нас" # Цей пункт буде підпунктом "Про нас"
    weight = 20
  [[menus.main]]
    name = "Новини"
    url = "/posts/"
    weight = 40